startCommand: gunicorn app:app
services:
  - type: web
    name: set-medic-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
